"""Add UUID column to bins table

Revision ID: 85de4b4bb118
Revises: e4979fbf68ba
Create Date: 2024-03-18 17:00:54.085648

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.sql import text

from core.utils.custom_utils import CustomUtils

# revision identifiers, used by Alembic.
revision: str = "85de4b4bb118"
down_revision: Union[str, None] = "e4979fbf68ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bins", sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )

    # Set UUID values for existing rows
    conn = op.get_bind()
    result = conn.execute(text("SELECT id FROM bins"))

    for row in result:
        conn.execute(
            text("UPDATE bins SET uuid = :uuid WHERE id = :id"),
            {"uuid": CustomUtils.generate_uuid("bin_"), "id": row.id},
        )

    # Set uuid column as not nullable
    op.alter_column("bins", "uuid", nullable=False)

    op.create_unique_constraint(None, "bins", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bins", type_="unique")
    op.drop_column("bins", "uuid")
    # ### end Alembic commands ###
